// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjydtGjm3Nq6n0sWkM193Yzsxg6OOL5cI',
    appId: '1:7959400256:web:ac58609d5ec2049b19f4a5',
    messagingSenderId: '7959400256',
    projectId: 'classwork--6',
    authDomain: 'classwork--6.firebaseapp.com',
    storageBucket: 'classwork--6.firebasestorage.app',
    measurementId: 'G-CY0J84LYZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHttZLtAb8oPau5sRBa_C7bthCvQYcI7Q',
    appId: '1:7959400256:android:d5efcd11c0aeb44419f4a5',
    messagingSenderId: '7959400256',
    projectId: 'classwork--6',
    storageBucket: 'classwork--6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxALryYaQ35Eh-gvvPUMW_rPG7G6djtkA',
    appId: '1:7959400256:ios:cc37185206b6eaf319f4a5',
    messagingSenderId: '7959400256',
    projectId: 'classwork--6',
    storageBucket: 'classwork--6.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxALryYaQ35Eh-gvvPUMW_rPG7G6djtkA',
    appId: '1:7959400256:ios:cc37185206b6eaf319f4a5',
    messagingSenderId: '7959400256',
    projectId: 'classwork--6',
    storageBucket: 'classwork--6.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjydtGjm3Nq6n0sWkM193Yzsxg6OOL5cI',
    appId: '1:7959400256:web:bba60c3e4ae479e219f4a5',
    messagingSenderId: '7959400256',
    projectId: 'classwork--6',
    authDomain: 'classwork--6.firebaseapp.com',
    storageBucket: 'classwork--6.firebasestorage.app',
    measurementId: 'G-6Z7T5XQW1T',
  );
}
